## Authentication [/authentication/login]
### Login [POST]

+ Request (application/json)

    + Body
        {
            "user": "leonir",
            "password": "123456"
        }

+ Response 200 (application/json)

    {
        "firstName": "Leonir",
        "lastName": "Deolindo"
    }