name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: macos-latest
    env:
      CCACHE_MAXSIZE: '100G'
      CCACHE_SLOPPINESS: 'clang_index_store,file_stat_matches,include_file_ctime,include_file_mtime,ivfsoverlay,pch_defines,modules,system_headers,time_macros'
      CCACHE_FILECLONE: true
      CCACHE_DEPEND: true
      CCACHE_INODECACHE: true
    steps:
      - uses: actions/checkout@v3
      - name: Cache ccache
        id: cache-ccache
        uses: actions/cache@v3
        with:
          path: /Users/$USER/Library/Caches/ccache
          key: ccache-${{ runner.os }}
          restore-keys: |
            ccache-${{ runner.os }}
            ccache-

      - if: ${{ steps.cache-ccache.outputs.cache-hit != 'true' }}
        name: Install ccache
        continue-on-error: true
        run: |
          brew install ccache

      - name: Install xcbeautify
        run: |
          brew install xcbeautify

      - name: Config ccache
        run: |
          ccache -p

      - name: Build Project
        run: |
          xcodebuild clean build \
            -project ListPublicGists.xcodeproj \
            -configuration Debug \
            -scheme ListPublicGists \
          | xcbeautify

      - name: Statis ccache
        run: |
          ccache -s