name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: macos-latest
    env:
      # CCACHE_MAXSIZE: '100G'
      CCACHE_CONFIGPATH: "ccache.conf"
    steps:
      - name: Install ccache
        run: |
          brew install ccache
      # - name: Config ccache
      #   run: |
      #     set -e -v
      #     export CCACHE_CONFIGPATH="ccache.conf"
      - name: Config ccache
        run: |
          ccache -p